// Generated by https://quicktype.io

export interface TopLevel {
    id_entrada?: number;
    id_usuario?: number;
    titulo?:     string;
    contenido?:  string;
    creado_en?:  Date;
}

export interface User{
    id_usuario: string;
    nombre_usuario: string;
    contrasena: string;
    correo_electronico: string; 
}
